apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx ## 사용자 지정 컨트롤러가 라우팅 규칙을 이해하도록 도울 것이다.
spec:
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts ## 해당 경로로 요청이 오면 4000번 포트로 이동시킨다.
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000