apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1 # 1개의 이미지에 대해 1개 pod을 생성
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: hyeongeol/msa-posts
          imagePullPolicy: IfNotPresent # 로컬 docker 에서만 이미지를 찾음
--- 
apiVersion: v1
kind: Service
metadata:
  name: post-cluster-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # nodePort
      targetPort: 4000

